[project]
name = 'decentralized-port-logistics-coordination'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cargo-handling-coordinator]
path = 'contracts/cargo-handling-coordinator.clar'
clarity_version = 3
epoch = 3.1

[contracts.vessel-scheduling-optimizer]
path = 'contracts/vessel-scheduling-optimizer.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
